#!/usr/bin/env python3
"""Generate the NES Wordle word data:
  build/words.bin   - validation dictionary, 3 bytes/word (24-bit base-26
                      packed, sorted ascending) for binary search.
  build/answers.bin - answer pool, 5 bytes/word (letter indices 0-25).
  src/words_gen.inc - WORD_COUNT / ANSWER_COUNT constants for the assembler.
A 5-letter word packs as value = ((((l0*26)+l1)*26+l2)*26+l3)*26+l4, which
is < 2^24, and sorting by that value == alphabetical order.
"""
import os

DICT = "/usr/share/dict/words"

# Curated common 5-letter answers (must all be real words; verified against
# the dictionary below). Trimmed to a power of two so the RNG pick is a mask.
ANSWERS = [
    "APPLE", "BEACH", "BERRY", "BRAIN", "BREAD", "BRICK", "BRUSH", "CHAIR",
    "CHARM", "CHESS", "CLOCK", "CLOUD", "CRANE", "DANCE", "DREAM", "DRINK",
    "EAGLE", "EARTH", "FLAME", "FLASH", "FRUIT", "GHOST", "GRAPE", "GRASS",
    "HEART", "HONEY", "HOUSE", "JUICE", "KNIFE", "LEMON", "LIGHT", "MAGIC",
    "MONEY", "MOUSE", "MUSIC", "NIGHT", "OCEAN", "PAINT", "PEACH", "PIANO",
    "PILOT", "PLANT", "PRIDE", "QUEEN", "RIVER", "ROBOT", "SHARK", "SHINE",
    "SMILE", "SNAKE", "SOUND", "SPACE", "SPARK", "STORM", "SUGAR", "SWORD",
    "TABLE", "TIGER", "TRAIN", "WATER", "WHALE", "WORLD", "YOUTH", "ZEBRA",
]

def pack(word):
    v = 0
    for ch in word:
        v = v * 26 + (ord(ch) - ord('A'))
    return v

def main():
    # Build the validation set from the system dictionary.
    words = set()
    with open(DICT) as f:
        for line in f:
            w = line.strip().upper()
            if len(w) == 5 and w.isalpha() and all('A' <= c <= 'Z' for c in w):
                words.add(w)
    # Make sure every answer is also a valid guess.
    for a in ANSWERS:
        words.add(a)

    packed = sorted(pack(w) for w in words)
    with open("build/words.bin", "wb") as f:
        for v in packed:
            f.write(bytes([(v >> 16) & 0xFF, (v >> 8) & 0xFF, v & 0xFF]))

    with open("build/answers.bin", "wb") as f:
        for w in ANSWERS:
            f.write(bytes(ord(c) - ord('A') for c in w))

    os.makedirs("src", exist_ok=True)
    with open("src/words_gen.inc", "w") as f:
        f.write("; generated by tools/make_words.py - do not edit\n")
        f.write("WORD_COUNT   = %d\n" % len(packed))
        f.write("ANSWER_COUNT = %d\n" % len(ANSWERS))

    print("validation words: %d  (%d bytes)" % (len(packed), len(packed) * 3))
    print("answer pool:      %d  (%d bytes)" % (len(ANSWERS), len(ANSWERS) * 5))
    print("PRG budget: 32768 bytes total (code + data must fit)")

if __name__ == "__main__":
    main()
