; ============================================================
; hello.s - Minimal NES ROM: palette + "HELLO NES" on screen.
; Proves the full build pipeline (ca65 -> ld65 -> .nes) works.
; ============================================================

; ---- iNES header (16 bytes) tells the emulator the cart layout ----
.segment "HEADER"
    .byte "NES", $1A      ; magic number
    .byte 2               ; PRG-ROM: 2 x 16KB = 32KB
    .byte 1               ; CHR-ROM: 1 x 8KB
    .byte $00             ; mapper 0 (NROM), horizontal mirroring
    .byte $00
    .byte 0,0,0,0,0,0,0,0 ; padding

; ---- Main code ----
.segment "CODE"

reset:
    sei                   ; disable IRQs
    cld                   ; disable decimal mode (NES has no BCD)
    ldx #$40
    stx $4017             ; disable APU frame counter IRQ
    ldx #$ff
    txs                   ; set up the stack pointer
    inx                   ; X = 0
    stx $2000             ; PPUCTRL = 0 -> NMI off
    stx $2001             ; PPUMASK = 0 -> rendering off
    stx $4010             ; disable DMC IRQs

    ; --- wait for the PPU to warm up (first vblank) ---
:   bit $2002
    bpl :-

    ; --- clear all 2KB of RAM to zero ---
    lda #$00
clear_ram:
    sta $0000, x
    sta $0100, x
    sta $0200, x
    sta $0300, x
    sta $0400, x
    sta $0500, x
    sta $0600, x
    sta $0700, x
    inx
    bne clear_ram

    ; --- wait for second vblank: PPU is now fully ready ---
:   bit $2002
    bpl :-

    ; --- load the palette into PPU $3F00 ---
    bit $2002             ; reset the $2006 address latch
    lda #$3f
    sta $2006
    lda #$00
    sta $2006
    ldx #$00
load_palette:
    lda palette, x
    sta $2007
    inx
    cpx #32
    bne load_palette

    ; --- write "HELLO NES" to the nametable ($2000 grid) ---
    ; Target tile = row 14, col 11 -> $2000 + 14*32 + 11 = $21CB
    bit $2002
    lda #$21
    sta $2006
    lda #$CB
    sta $2006
    ldx #$00
load_text:
    lda message, x
    beq text_done         ; stop at the 0 terminator
    sta $2007
    inx
    jmp load_text
text_done:

    ; --- turn rendering back on ---
    lda #%10000000        ; enable NMI, background uses pattern table 0
    sta $2000
    lda #%00001110        ; show background (and left column)
    sta $2001

forever:
    jmp forever           ; spin; the NMI handler does the per-frame work

; NMI fires once per frame (vblank). Nothing to do yet.
nmi:
    rti

irq:
    rti

; ---- Read-only data ----
.segment "RODATA"

palette:
    ; Background palette 0: black bg, then white/yellow/green text colors
    .byte $0f, $30, $28, $1a
    .byte $0f, $30, $28, $1a
    .byte $0f, $30, $28, $1a
    .byte $0f, $30, $28, $1a
    ; Sprite palettes (unused for now)
    .byte $0f, $30, $28, $1a
    .byte $0f, $30, $28, $1a
    .byte $0f, $30, $28, $1a
    .byte $0f, $30, $28, $1a

message:
    .byte "HELLO NES", $00   ; ASCII bytes == tile indices in our CHR font

; ---- The tile/font data generated by tools/make_chr.py ----
.segment "CHARS"
    .incbin "build/wordle.chr"

; ---- CPU interrupt vectors live at the very top of memory ----
.segment "VECTORS"
    .word nmi
    .word reset
    .word irq
