; ============================================================
; wordle.s - NES Wordle (work in progress)
; Step 3: enter letters into row 0 with the controller.
;   D-pad Up   = next letter (A->B->C...)
;   D-pad Down = previous letter
;   A          = confirm letter, move to next box
;   B          = backspace
; ============================================================

; ---- Board geometry (in 8x8 tiles) ----
START_COL = 6
START_ROW = 2              ; even row so each 2x2 cell owns one attribute block
STRIDE    = 4              ; 2-tile cell + 2-tile gap

; Result palette numbers used by the attribute table
PAL_GREEN  = 1
PAL_YELLOW = 2
PAL_GRAY   = 3

; Message ids (index into the 12-char message strings)
MSG_NONE    = 0
MSG_NOTWORD = 1
MSG_WIN     = 2
MSG_LOSE    = 3

; WORD_COUNT and ANSWER_COUNT, generated by tools/make_words.py
.include "words_gen.inc"

; Empty-cell box-outline tiles (from make_chr.py)
TILE_TL = $5B
TILE_TR = $5C
TILE_BL = $5D
TILE_BR = $5E
BIG_BASE = $60            ; big letter L occupies tiles $60 + L*4 .. +3
SMALL_FILLED_BASE = $DC   ; small filled keyboard letter L at $DC + L
EMPTY    = $FF            ; cell_letter sentinel meaning "draw empty box"

; On-screen keyboard: A-M on tile row 24, N-Z on tile row 26, first col 4
KB_COL  = 4
KB_ROW0 = 24
KB_ROW1 = 26

; RAM (page 3, zeroed by clear_ram)
kbd_attr  = $0340         ; 8-byte shadow of the keyboard's attribute bytes
key_state = $0350         ; per-letter best rank (0 none,1 gray,2 yellow,3 green)

; ---- Controller button bit masks (read order A,B,Sel,Start,U,D,L,R) ----
BTN_A     = $80
BTN_B     = $40
BTN_SEL   = $20
BTN_START = $10
BTN_UP    = $08
BTN_DOWN  = $04
BTN_LEFT  = $02
BTN_RIGHT = $01

; ---- Zero-page variables ----
.segment "ZEROPAGE"
ppu_lo:        .res 1
ppu_hi:        .res 1
tile_x:        .res 1
tile_y:        .res 1
cur_col:       .res 1     ; draw_board scratch
cur_row:       .res 1
cell_col:      .res 1     ; draw_cell inputs
cell_row:      .res 1
cell_letter:   .res 1
t0:            .res 1     ; the four tiles to write for a cell
t1:            .res 1
t2:            .res 1
t3:            .res 1
pad:           .res 1     ; controller state this frame
pad_prev:      .res 1     ; controller state last frame
pressed:       .res 1     ; buttons newly pressed this frame
g_col:         .res 1     ; active column in the current row (0-4)
g_row:         .res 1     ; current guess row (0-5)
g_letter:      .res 1     ; letter index shown in the active cell (0-25)
clear_pending: .res 1     ; NMI should blank a cell this frame
clear_col:     .res 1
frame_flag:    .res 1     ; set by NMI each vblank (frame sync)
row_letters:   .res 5     ; letter index entered in each column of the row
row_pal:       .res 5     ; per-column result palette after a guess
used:          .res 5     ; answer positions consumed during scoring
win_flag:      .res 1     ; set when a guess is all-green
game_over:     .res 1     ; nonzero -> ignore further input
submit_row:    .res 1     ; row whose colors the NMI should flush
submit_flush:  .res 1     ; NMI should write this row's attribute colors
attr_lo:       .res 1     ; scratch for attribute address
answer:        .res 5     ; this game's secret word (letter indices)
rng:           .res 1     ; free-running random seed (LFSR)
seeded:        .res 1     ; whether the answer has been chosen
msg_id:        .res 1     ; which message to show (MSG_*)
msg_dirty:     .res 1     ; NMI should (re)draw the message line
gp_lo:         .res 1     ; packed guess value (24-bit, big end in gp_hi)
gp_mid:        .res 1
gp_hi:         .res 1
mtmp_lo:       .res 1     ; multiply temporaries
mtmp_mid:      .res 1
mtmp_hi:       .res 1
srch_lo:       .res 2     ; binary-search bounds (16-bit)
srch_hi:       .res 2
srch_mid:      .res 2
ptr:           .res 2     ; general 16-bit pointer
msg_ptr:       .res 2     ; pointer used by the NMI message draw
off_lo:        .res 1
off_hi:        .res 1
blink_ctr:     .res 1     ; cursor blink frame counter
blink_on:      .res 1     ; cursor blink phase (1 = show letter)
commit_pending:.res 1     ; NMI should permanently draw a just-finished cell
commit_col:    .res 1
commit_row:    .res 1
commit_let:    .res 1
kbd_dirty:     .res 1     ; NMI should copy kbd_attr -> VRAM
kt_a:          .res 1     ; keyboard geometry scratch
kt_b:          .res 1
kt_c:          .res 1
kt_d:          .res 1
state:         .res 1     ; 0 = title screen, 1 = playing

; ---- iNES header ----
.segment "HEADER"
    .byte "NES", $1A
    .byte 2               ; 32KB PRG
    .byte 1               ; 8KB CHR
    .byte $00             ; mapper 0, horizontal mirroring
    .byte $00
    .byte 0,0,0,0,0,0,0,0

.segment "CODE"

reset:
    sei
    cld
    ldx #$40
    stx $4017
    ldx #$ff
    txs
    inx
    stx $2000             ; NMI off
    stx $2001             ; rendering off
    stx $4010

:   bit $2002             ; wait for first vblank
    bpl :-

    lda #$00              ; clear 2KB RAM (also zeroes all our variables)
clear_ram:
    sta $0000, x
    sta $0100, x
    sta $0200, x
    sta $0300, x
    sta $0400, x
    sta $0500, x
    sta $0600, x
    sta $0700, x
    inx
    bne clear_ram

    lda #$a5              ; seed the RNG (an LFSR must start nonzero)
    sta rng
    lda #1                ; start with the cursor letter visible
    sta blink_on

:   bit $2002             ; wait for second vblank
    bpl :-

    ; ---- load palette ----
    bit $2002
    lda #$3f
    sta $2006
    lda #$00
    sta $2006
    ldx #$00
load_palette:
    lda palette, x
    sta $2007
    inx
    cpx #32
    bne load_palette

    ; ---- draw the title (home) screen (rendering still off) ----
    jsr draw_title_screen

    ; ---- point PPU address back to top-left so the screen isn't scrolled ----
    lda #%10000000        ; NMI on, BG pattern table 0, nametable 0
    sta $2000
    bit $2002
    lda #$20
    sta $2006
    lda #$00
    sta $2006
    sta $2005
    sta $2005

    ; ---- enable rendering ----
    lda #%00001110
    sta $2001

; ---- main loop: one pass per frame, synced to the NMI ----
mainloop:
    lda frame_flag
    beq mainloop
    lda #$00
    sta frame_flag
    jsr read_controller
    jsr handle_input
    jmp mainloop

; ------------------------------------------------------------
; read_controller - latch and shift 8 bits from $4016 into pad.
; After this, pad bit7=A, bit6=B, ... bit0=Right.
; ------------------------------------------------------------
read_controller:
    lda #$01
    sta $4016
    lda #$00
    sta $4016
    ldx #8
@loop:
    lda $4016
    lsr a                 ; button state -> carry
    rol pad               ; carry -> low bit of pad (shifts left each read)
    dex
    bne @loop
    rts

; ------------------------------------------------------------
; handle_input - act on newly pressed buttons.
; ------------------------------------------------------------
handle_input:
    lda pad_prev          ; pressed = pad AND (NOT pad_prev)
    eor #$ff
    and pad
    sta pressed
    lda pad
    sta pad_prev

    lda state             ; title screen: any press starts a new game
    bne @playing
    lda pressed
    beq @title_rts
    jsr new_game
@title_rts:
    rts
@playing:

    lda game_over         ; when the game is over, wait for a restart press
    beq @live
    lda pressed
    and #(BTN_START | BTN_A | BTN_RIGHT)
    beq @over_rts
    jsr new_game
@over_rts:
    rts
@live:

    lda pressed           ; nothing pressed -> nothing to do
    bne @has_press
    jmp @input_done
@has_press:

    lda seeded            ; choose the secret word on the very first press
    bne @have_answer
    jsr choose_answer
    lda #1
    sta seeded
@have_answer:

    lda msg_id            ; clear a stale "NOT A WORD" message on any press
    cmp #MSG_NOTWORD
    bne @no_msg_clear
    lda #MSG_NONE
    sta msg_id
    lda #1
    sta msg_dirty
@no_msg_clear:

    ; --- Up: next letter ---
    lda pressed
    and #BTN_UP
    beq @not_up
    ldx g_col
    lda row_letters, x
    clc
    adc #1
    cmp #26
    bne @up_ok
    lda #0
@up_ok:
    sta row_letters, x
    sta g_letter
@not_up:

    ; --- Down: previous letter ---
    lda pressed
    and #BTN_DOWN
    beq @not_down
    ldx g_col
    lda row_letters, x
    sec
    sbc #1
    bpl @down_ok          ; >= 0 keeps value; underflow ($FF) wraps to 25
    lda #25
@down_ok:
    sta row_letters, x
    sta g_letter
@not_down:

    ; --- A or Right: confirm letter, advance to next box ---
    lda pressed
    and #(BTN_A | BTN_RIGHT)
    beq @not_a
    lda g_col
    cmp #4
    bcs @not_a            ; on last box -> fall through so Right/Start submits
    jsr commit_current    ; lock the finished box so it stays drawn
    inc g_col
    ldx g_col
    lda #0
    sta row_letters, x    ; new box starts at 'A'
    sta g_letter
    jmp @input_done       ; advanced this frame; don't also submit
@not_a:

    ; --- B or Left: backspace ---
    lda pressed
    and #(BTN_B | BTN_LEFT)
    beq @not_b
    lda g_col
    beq @not_b            ; nothing to delete at the first box
    sta clear_col         ; queue blanking of the current box
    lda #1
    sta clear_pending
    dec g_col
    ldx g_col
    lda row_letters, x    ; reactivate the previous box's letter
    sta g_letter
@not_b:

    ; --- Start or Right (on the last box): submit the guess ---
    lda pressed
    and #(BTN_START | BTN_RIGHT)
    beq @not_start
    lda g_col
    cmp #4
    bne @not_start        ; row not full yet

    jsr is_valid_word     ; A=1 if the guess is in the dictionary
    bne @valid
    lda #MSG_NOTWORD      ; reject it, show "NOT A WORD"
    sta msg_id
    lda #1
    sta msg_dirty
    rts
@valid:
    jsr commit_current    ; lock the last box so it's drawn before coloring
    jsr evaluate_guess    ; fills row_pal[], sets win_flag
    jsr update_keys       ; fold the result into the keyboard letter states
    jsr color_keyboard
    lda g_row
    sta submit_row        ; tell the NMI which row's colors to paint
    lda #1
    sta submit_flush
    lda win_flag
    bne @win
    lda g_row
    cmp #5
    beq @lose             ; was the last row -> out of guesses
    ; advance to a fresh next row
    inc g_row
    lda #0
    sta g_col
    sta g_letter
    ldx #4
@clear_row:
    sta row_letters, x
    dex
    bpl @clear_row
    rts
@win:
    lda #MSG_WIN
    sta msg_id
    lda #1
    sta msg_dirty
    sta game_over
    rts
@lose:
    lda #MSG_LOSE
    sta msg_id
    lda #1
    sta msg_dirty
    sta game_over
@not_start:
@input_done:
    rts

; ------------------------------------------------------------
; evaluate_guess - score row_letters against answer_data using
; standard Wordle rules (greens first, then yellows on remaining
; answer letters). Fills row_pal[0..4] and sets win_flag.
; ------------------------------------------------------------
evaluate_guess:
    ; pass 1: greens (and mark which answer slots are used)
    ldx #0
@p1:
    lda row_letters, x
    cmp answer, x
    bne @p1_miss
    lda #PAL_GREEN
    sta row_pal, x
    lda #1
    sta used, x
    jmp @p1_next
@p1_miss:
    lda #PAL_GRAY
    sta row_pal, x
    lda #0
    sta used, x
@p1_next:
    inx
    cpx #5
    bne @p1

    ; pass 2: yellows (each guess letter consumes one unused answer slot)
    ldx #0
@p2:
    lda row_pal, x
    cmp #PAL_GREEN
    beq @p2_next          ; already green
    ldy #0
@search:
    lda used, y
    bne @search_next      ; that answer slot already taken
    lda answer, y
    cmp row_letters, x
    bne @search_next
    lda #PAL_YELLOW       ; match in the wrong spot
    sta row_pal, x
    lda #1
    sta used, y
    jmp @p2_next
@search_next:
    iny
    cpy #5
    bne @search
@p2_next:
    inx
    cpx #5
    bne @p2

    ; win = all five green
    lda #1
    sta win_flag
    ldx #0
@wc:
    lda row_pal, x
    cmp #PAL_GREEN
    beq @wc_next
    lda #0
    sta win_flag
@wc_next:
    inx
    cpx #5
    bne @wc
    rts

; ------------------------------------------------------------
; choose_answer - copy a random word from answer_pool into answer[].
; Index = rng & (ANSWER_COUNT-1); pool entries are 5 bytes each.
; ------------------------------------------------------------
choose_answer:
    lda rng
    and #(ANSWER_COUNT-1)
    sta off_lo            ; idx
    asl a
    asl a                 ; idx*4 (fits 8 bits for idx<=63)
    clc
    adc off_lo            ; idx*5 (can exceed 255)
    sta off_lo
    lda #0
    adc #0
    sta off_hi            ; carry -> high byte of offset
    clc
    lda #<answer_pool
    adc off_lo
    sta ptr
    lda #>answer_pool
    adc off_hi
    sta ptr+1
    ldy #0
@copy:
    lda (ptr), y
    sta answer, y
    iny
    cpy #5
    bne @copy
    rts

; ------------------------------------------------------------
; pack_guess - pack row_letters[0..4] into the 24-bit value
; gp_hi:gp_mid:gp_lo using value = value*26 + letter.
; ------------------------------------------------------------
pack_guess:
    lda #0
    sta gp_lo
    sta gp_mid
    sta gp_hi
    ldx #0
@loop:
    jsr gp_times26
    lda row_letters, x    ; add the next letter
    clc
    adc gp_lo
    sta gp_lo
    lda gp_mid
    adc #0
    sta gp_mid
    lda gp_hi
    adc #0
    sta gp_hi
    inx
    cpx #5
    bne @loop
    rts

; gp = gp * 26  (24-bit), via adding a saved copy 26 times.
gp_times26:
    lda gp_lo
    sta mtmp_lo
    lda gp_mid
    sta mtmp_mid
    lda gp_hi
    sta mtmp_hi
    lda #0
    sta gp_lo
    sta gp_mid
    sta gp_hi
    ldy #26
@add:
    clc
    lda gp_lo
    adc mtmp_lo
    sta gp_lo
    lda gp_mid
    adc mtmp_mid
    sta gp_mid
    lda gp_hi
    adc mtmp_hi
    sta gp_hi
    dey
    bne @add
    rts

; ------------------------------------------------------------
; is_valid_word - binary search the packed guess in words_data.
; Returns A=1 (valid) or A=0 (not found). words_data is sorted
; ascending, 3 bytes (big-endian) per word, WORD_COUNT entries.
; ------------------------------------------------------------
is_valid_word:
    jsr pack_guess
    lda #0                ; lo = 0
    sta srch_lo
    sta srch_lo+1
    lda #<WORD_COUNT      ; hi = WORD_COUNT (exclusive)
    sta srch_hi
    lda #>WORD_COUNT
    sta srch_hi+1
@loop:
    lda srch_lo+1         ; while lo < hi
    cmp srch_hi+1
    bcc @cont             ; lo_hi < hi_hi
    bne @notfound         ; lo_hi > hi_hi
    lda srch_lo
    cmp srch_hi
    bcs @notfound         ; lo >= hi
@cont:
    clc                   ; mid = (lo + hi) / 2
    lda srch_lo
    adc srch_hi
    sta srch_mid
    lda srch_lo+1
    adc srch_hi+1
    sta srch_mid+1
    lsr srch_mid+1
    ror srch_mid
    ; ptr = words_data + mid*3
    lda srch_mid
    asl a
    sta off_lo
    lda srch_mid+1
    rol a
    sta off_hi            ; off = mid*2
    clc
    lda off_lo
    adc srch_mid
    sta off_lo
    lda off_hi
    adc srch_mid+1
    sta off_hi           ; off = mid*3
    clc
    lda #<words_data
    adc off_lo
    sta ptr
    lda #>words_data
    adc off_hi
    sta ptr+1
    ; compare entry (big-endian) vs gp
    ldy #0
    lda (ptr), y
    cmp gp_hi
    bcc @set_lo           ; entry < gp
    bne @set_hi           ; entry > gp
    iny
    lda (ptr), y
    cmp gp_mid
    bcc @set_lo
    bne @set_hi
    iny
    lda (ptr), y
    cmp gp_lo
    bcc @set_lo
    bne @set_hi
    lda #1               ; equal -> found
    rts
@set_lo:                 ; lo = mid + 1
    clc
    lda srch_mid
    adc #1
    sta srch_lo
    lda srch_mid+1
    adc #0
    sta srch_lo+1
    jmp @loop
@set_hi:                 ; hi = mid
    lda srch_mid
    sta srch_hi
    lda srch_mid+1
    sta srch_hi+1
    jmp @loop
@notfound:
    lda #0
    rts

; ------------------------------------------------------------
; commit_current - queue the active cell to be drawn permanently with its
; letter (so it isn't left blanked by the cursor blink when we move away).
; ------------------------------------------------------------
commit_current:
    lda g_col
    sta commit_col
    lda g_row
    sta commit_row
    ldx g_col
    lda row_letters, x
    sta commit_let
    lda #1
    sta commit_pending
    rts

; ------------------------------------------------------------
; draw_keyboard - draw all 26 small filled letters A-Z (rendering off).
; Letter L: row 24 (L<13) or 26, column KB_COL + (L mod 13)*2.
; ------------------------------------------------------------
draw_keyboard:
    ldx #0
@loop:
    txa
    cmp #13
    bcc @row0
    sbc #13               ; within-row index (carry set by cmp)
    pha
    lda #$40              ; row 26 low byte ($2340)
    sta kt_a
    pla
    jmp @havecol
@row0:
    pha
    lda #$00              ; row 24 low byte ($2300)
    sta kt_a
    pla
@havecol:
    asl a                 ; (idx)*2
    clc
    adc #KB_COL           ; column
    clc
    adc kt_a              ; + row base low
    sta kt_a
    bit $2002
    lda #$23
    sta $2006
    lda kt_a
    sta $2006
    txa
    clc
    adc #SMALL_FILLED_BASE
    sta $2007
    inx
    cpx #26
    bne @loop
    rts

; ------------------------------------------------------------
; update_keys - fold the last guess result into key_state[]. For each
; column, rank = 4 - palette (green=3 > yellow=2 > gray=1); keep the max.
; ------------------------------------------------------------
update_keys:
    ldx #0
@loop:
    lda #4
    sec
    sbc row_pal, x        ; rank
    ldy row_letters, x
    cmp key_state, y
    bcc @skip             ; new rank lower -> keep old
    sta key_state, y
@skip:
    inx
    cpx #5
    bne @loop
    rts

; ------------------------------------------------------------
; color_keyboard - rebuild kbd_attr[] from key_state[] and flag the NMI.
; Each letter sets the 2 palette bits of its attribute-table quadrant.
; ------------------------------------------------------------
color_keyboard:
    ldx #7
    lda #0
@clr:
    sta kbd_attr, x
    dex
    bpl @clr
    ldx #0                ; X = letter L
@loop:
    txa
    cmp #13
    bcc @row0
    sbc #13               ; within-row index
    ldy #1                ; quad_y = 1 (row 26)
    jmp @havecol
@row0:
    ldy #0                ; quad_y = 0 (row 24)
@havecol:
    sty kt_d              ; stash quad_y
    asl a
    clc
    adc #KB_COL           ; c = KB_COL + idx*2
    sta kt_a              ; c
    lsr a
    lsr a                 ; c >> 2
    sta kt_b              ; kbd_attr index
    lda kt_a
    and #2
    lsr a                 ; quad_x (0/1)
    sta kt_c
    lda kt_d              ; quad_y
    asl a                 ; *2
    clc
    adc kt_c              ; quad_y*2 + quad_x
    asl a                 ; * 2 -> shift (0,2,4,6)
    sta kt_d              ; shift
    ldy key_state, x      ; rank 0-3
    lda state_pal, y      ; palette 0-3
    ldy kt_d
    beq @noshift
@shloop:
    asl a
    dey
    bne @shloop
@noshift:
    ldy kt_b
    ora kbd_attr, y
    sta kbd_attr, y
    inx
    cpx #26
    bne @loop
    lda #1
    sta kbd_dirty
    rts

; ------------------------------------------------------------
; clear_nametable - fill nametable 0 + its attributes with blank tiles.
; Must run with rendering off.
; ------------------------------------------------------------
clear_nametable:
    bit $2002
    lda #$20
    sta $2006
    lda #$00
    sta $2006
    ldx #0
    ldy #4
    lda #$00              ; blank tile
@fill:
    sta $2007
    inx
    bne @fill
    dey
    bne @fill             ; 4 * 256 = 1024 bytes ($2000-$23FF)
    rts

; ------------------------------------------------------------
; new_game - clear the screen and start a fresh round (from the title
; screen or after game over). Runs with rendering off, then re-enables.
; ------------------------------------------------------------
new_game:
    lda #0
    sta $2000             ; NMI off
    sta $2001             ; rendering off

    sta g_col             ; reset all game state
    sta g_row
    sta g_letter
    sta game_over
    sta seeded            ; next press chooses a fresh answer
    sta clear_pending
    sta submit_flush
    sta commit_pending
    sta msg_id
    sta msg_dirty
    sta kbd_dirty
    ldx #4
@clr_letters:
    sta row_letters, x
    dex
    bpl @clr_letters
    ldx #25
    lda #0
@clr_keys:
    sta key_state, x
    dex
    bpl @clr_keys

    jsr clear_nametable   ; wipe the whole screen (title art or old board)
    jsr draw_title        ; small "WORDLE" header
    jsr draw_board
    jsr draw_keyboard

    lda #1                ; now playing
    sta state

    lda #%10000000        ; reset scroll, re-enable NMI + rendering
    sta $2000
    bit $2002
    lda #$20
    sta $2006
    lda #$00
    sta $2006
    sta $2005
    sta $2005
    lda #%00001110
    sta $2001
    rts

; ------------------------------------------------------------
; draw_title_screen - the home screen: big "WORDLE" + a start prompt.
; Runs with rendering off.
; ------------------------------------------------------------
draw_title_screen:
    jsr clear_nametable

    ; big "WORDLE" across tile row 10 (letters at cols 10,12,...,20)
    ldx #0
@big_loop:
    lda title_big_cols, x
    sta kt_a              ; tile column
    ; top row of the big letter at $2000 + 10*32 + col = $2140 + col
    bit $2002
    lda #$21
    sta $2006
    lda #$40
    clc
    adc kt_a
    sta $2006
    lda title_big_let, x  ; letter index -> base tile
    asl a
    asl a
    clc
    adc #BIG_BASE
    sta kt_b              ; TL tile
    sta $2007             ; TL
    clc
    adc #1
    sta $2007             ; TR
    ; bottom row (+32 tiles) at $2160 + col
    bit $2002
    lda #$21
    sta $2006
    lda #$60
    clc
    adc kt_a
    sta $2006
    lda kt_b
    clc
    adc #2
    sta $2007             ; BL
    clc
    adc #1
    sta $2007             ; BR
    inx
    cpx #6
    bne @big_loop

    ; "PUSH START" centered on tile row 18 ($2000 + 18*32 + 11 = $224B)
    bit $2002
    lda #$22
    sta $2006
    lda #$4B
    sta $2006
    ldx #0
@p1:
    lda prompt1, x
    beq @p1done
    sta $2007
    inx
    jmp @p1
@p1done:

    ; "OR PRESS RIGHT" on tile row 20 ($2000 + 20*32 + 9 = $2289)
    bit $2002
    lda #$22
    sta $2006
    lda #$89
    sta $2006
    ldx #0
@p2:
    lda prompt2, x
    beq @p2done
    sta $2007
    inx
    jmp @p2
@p2done:
    rts

; ------------------------------------------------------------
; draw_cell - draw the 2x2 cell at (cell_col, cell_row).
; cell_letter = 0-25 for a big letter, or EMPTY ($FF) for a box.
; Writes to the PPU, so it must run during vblank (called from NMI).
; ------------------------------------------------------------
draw_cell:
    ; tile_x = START_COL + cell_col*4
    lda cell_col
    asl a
    asl a
    clc
    adc #START_COL
    sta tile_x
    ; tile_y = START_ROW + cell_row*4
    lda cell_row
    asl a
    asl a
    clc
    adc #START_ROW
    sta tile_y
    ; ppu addr = $2000 + tile_y*32 + tile_x
    lda #0
    sta ppu_hi
    lda tile_y
    ldx #5
@mul:
    asl a
    rol ppu_hi
    dex
    bne @mul
    clc
    adc tile_x
    sta ppu_lo
    lda ppu_hi
    adc #0
    clc
    adc #$20
    sta ppu_hi

    ; pick the four tiles
    lda cell_letter
    cmp #EMPTY
    bne @as_letter
    lda #TILE_TL
    sta t0
    lda #TILE_TR
    sta t1
    lda #TILE_BL
    sta t2
    lda #TILE_BR
    sta t3
    jmp @write
@as_letter:
    lda cell_letter
    asl a
    asl a
    clc
    adc #BIG_BASE         ; t0 = $60 + letter*4
    sta t0
    tax
    inx
    stx t1
    inx
    stx t2
    inx
    stx t3
@write:
    ; top row: t0, t1
    bit $2002
    lda ppu_hi
    sta $2006
    lda ppu_lo
    sta $2006
    lda t0
    sta $2007
    lda t1
    sta $2007
    ; bottom row at +32
    lda ppu_lo
    clc
    adc #32
    sta ppu_lo
    lda ppu_hi
    adc #0
    sta ppu_hi
    bit $2002
    lda ppu_hi
    sta $2006
    lda ppu_lo
    sta $2006
    lda t2
    sta $2007
    lda t3
    sta $2007
    rts

; ------------------------------------------------------------
; draw_title - "WORDLE" near the top.
; ------------------------------------------------------------
draw_title:
    bit $2002
    lda #$20
    sta $2006
    lda #$2D
    sta $2006
    ldx #$00
@loop:
    lda title_text, x
    beq @done
    sta $2007
    inx
    jmp @loop
@done:
    rts

; ------------------------------------------------------------
; draw_board - 6x5 grid of empty 2x2 boxes (called with rendering off).
; ------------------------------------------------------------
draw_board:
    lda #0
    sta cur_row
@row_loop:
    lda #0
    sta cur_col
@col_loop:
    lda cur_col
    asl a
    asl a
    clc
    adc #START_COL
    sta tile_x
    lda cur_row
    asl a
    asl a
    clc
    adc #START_ROW
    sta tile_y

    lda #0
    sta ppu_hi
    lda tile_y
    ldx #5
@mul:
    asl a
    rol ppu_hi
    dex
    bne @mul
    clc
    adc tile_x
    sta ppu_lo
    lda ppu_hi
    adc #0
    clc
    adc #$20
    sta ppu_hi

    bit $2002
    lda ppu_hi
    sta $2006
    lda ppu_lo
    sta $2006
    lda #TILE_TL
    sta $2007
    lda #TILE_TR
    sta $2007

    lda ppu_lo
    clc
    adc #32
    sta ppu_lo
    lda ppu_hi
    adc #0
    sta ppu_hi

    bit $2002
    lda ppu_hi
    sta $2006
    lda ppu_lo
    sta $2006
    lda #TILE_BL
    sta $2007
    lda #TILE_BR
    sta $2007

    inc cur_col
    lda cur_col
    cmp #5
    bne @col_loop

    inc cur_row
    lda cur_row
    cmp #6
    bne @row_loop
    rts

; ------------------------------------------------------------
; NMI - runs every vblank: flush cell updates, reset scroll, sync.
; ------------------------------------------------------------
nmi:
    pha
    txa
    pha
    tya
    pha

    ; blank a vacated cell if backspace queued one
    lda clear_pending
    beq @no_clear
    lda #0
    sta clear_pending
    lda clear_col
    sta cell_col
    lda g_row
    sta cell_row
    lda #EMPTY
    sta cell_letter
    jsr draw_cell
@no_clear:

    ; permanently draw a just-committed cell (its letter, no blink)
    lda commit_pending
    beq @no_commit
    lda #0
    sta commit_pending
    lda commit_col
    sta cell_col
    lda commit_row
    sta cell_row
    lda commit_let
    sta cell_letter
    jsr draw_cell
@no_commit:

    ; advance the cursor blink phase (~16 frames per toggle)
    inc blink_ctr
    lda blink_ctr
    cmp #16
    bcc @blink_done
    lda #0
    sta blink_ctr
    lda blink_on
    eor #1
    sta blink_on
@blink_done:

    ; redraw the active cell, blinking between its letter and an empty box.
    ; Skipped on the title screen and once the game is over.
    lda state
    beq @no_active
    lda game_over
    bne @no_active
    lda g_col
    sta cell_col
    lda g_row
    sta cell_row
    lda blink_on
    bne @show_letter
    lda #EMPTY
    jmp @set_active
@show_letter:
    lda g_letter
@set_active:
    sta cell_letter
    jsr draw_cell
@no_active:

    ; paint a submitted row's colors into the attribute table
    lda submit_flush
    beq @no_submit
    lda #0
    sta submit_flush
    lda submit_row
    asl a
    asl a
    asl a                 ; submit_row * 8
    clc
    adc #$C1              ; base = $23C1 + row*8 (cell attribute bytes)
    sta attr_lo
    ldx #0
@attr_loop:
    bit $2002
    lda #$23
    sta $2006
    txa
    clc
    adc attr_lo
    sta $2006             ; address of this cell's attribute byte
    lda row_pal, x
    asl a
    asl a
    asl a
    asl a
    asl a
    asl a                 ; palette in bits 6-7 (bottom-right quadrant)
    sta $2007
    inx
    cpx #5
    bne @attr_loop
@no_submit:

    ; draw the status message line if it changed
    lda msg_dirty
    beq @no_msg
    lda #0
    sta msg_dirty
    lda msg_id            ; msg_ptr = messages + msg_id*12
    asl a
    asl a
    sta t0                ; id*4
    asl a                 ; id*8
    clc
    adc t0                ; id*12
    clc
    adc #<messages
    sta msg_ptr
    lda #>messages
    adc #0
    sta msg_ptr+1
    bit $2002
    lda #$23
    sta $2006
    lda #$8A              ; row 28, col 10
    sta $2006
    ldy #0
@msg_loop:
    lda (msg_ptr), y
    sta $2007
    iny
    cpy #12
    bne @msg_loop
@no_msg:

    ; copy the keyboard's attribute colors to VRAM if they changed
    lda kbd_dirty
    beq @no_kbd
    lda #0
    sta kbd_dirty
    bit $2002
    lda #$23
    sta $2006
    lda #$f0              ; attribute bytes 48-55 ($23F0) = keyboard rows
    sta $2006
    ldx #0
@kbd_loop:
    lda kbd_attr, x
    sta $2007
    inx
    cpx #8
    bne @kbd_loop
@no_kbd:

    ; advance the RNG one step every frame (8-bit Galois LFSR)
    lda rng
    lsr a
    bcc @no_xor
    eor #$b8
@no_xor:
    sta rng

    ; reset PPU address (scroll) to top-left
    lda #%10000000
    sta $2000
    bit $2002
    lda #$20
    sta $2006
    lda #$00
    sta $2006
    sta $2005
    sta $2005

    lda #1
    sta frame_flag

    pla
    tay
    pla
    tax
    pla
    rti

irq:
    rti

; ---- read-only data ----
.segment "RODATA"

palette:
    ; Each: backdrop, fill (color1), unused (color2), letter/outline (color3=white)
    .byte $0f, $0f, $0f, $30     ; pal0 neutral: black fill  -> white letter on black
    .byte $0f, $1a, $0f, $30     ; pal1 green
    .byte $0f, $28, $0f, $30     ; pal2 yellow
    .byte $0f, $00, $0f, $30     ; pal3 gray
    .byte $0f, $0f, $0f, $30     ; sprite palettes (unused)
    .byte $0f, $0f, $0f, $30
    .byte $0f, $0f, $0f, $30
    .byte $0f, $0f, $0f, $30

title_text:
    .byte "WORDLE", $00

; Title-screen big "WORDLE": letter indices and their tile columns
title_big_let:
    .byte 22, 14, 17, 3, 11, 4     ; W O R D L E
title_big_cols:
    .byte 10, 12, 14, 16, 18, 20

prompt1:
    .byte "PUSH START", $00
prompt2:
    .byte "OR PRESS RIGHT", $00

; key rank (0 none,1 gray,2 yellow,3 green) -> palette number
state_pal:
    .byte 0, PAL_GRAY, PAL_YELLOW, PAL_GREEN

; 12-char status messages, indexed by MSG_* (space-padded, drawn at row 27).
messages:
    .byte "            "         ; MSG_NONE  (clears the line)
    .byte " NOT A WORD "         ; MSG_NOTWORD
    .byte "  YOU WIN!  "         ; MSG_WIN
    .byte "  YOU LOSE  "         ; MSG_LOSE

; Curated answer pool: ANSWER_COUNT words, 5 letter-indices each.
answer_pool:
    .incbin "build/answers.bin"

; Validation dictionary: WORD_COUNT words, 3-byte big-endian packed, sorted.
words_data:
    .incbin "build/words.bin"

.segment "CHARS"
    .incbin "build/wordle.chr"

.segment "VECTORS"
    .word nmi
    .word reset
    .word irq
